#lang racket

(require racket/bytes
         racket/list
         racket/string)

(struct evt (tick kind chan a b) #:transparent)
(struct note (track chan pitch start end) #:transparent)

;; ---------- MIDI parsing ----------
(define (read-u16be b pos)
  (values (integer-bytes->integer (subbytes b pos (+ pos 2)) #f #t) (+ pos 2)))

(define (read-u32be b pos)
  (values (integer-bytes->integer (subbytes b pos (+ pos 4)) #f #t) (+ pos 4)))

(define (read-vlq b pos)
  (let loop ([p pos] [acc 0])
    (define v (bytes-ref b p))
    (define next (add1 p))
    (define acc* (+ (arithmetic-shift acc 7) (bitwise-and v #x7F)))
    (if (zero? (bitwise-and v #x80))
        (values acc* next)
        (loop next acc*))))

(define (parse-track-data data)
  (define len (bytes-length data))
  (define pos 0)
  (define abs-tick 0)
  (define running #f)
  (define events '())
  (define (push! e) (set! events (cons e events)))
  (let loop ()
    (when (< pos len)
      (define-values (delta p1) (read-vlq data pos))
      (set! pos p1)
      (set! abs-tick (+ abs-tick delta))
      (define status (bytes-ref data pos))
      (define data1 #f)
      (cond
        [(< status #x80)
         (unless running
           (error 'parse-track-data "running status without prior status"))
         (set! data1 status)
         (set! status running)
         (set! pos (add1 pos))]
        [else
         (set! running status)
         (set! pos (add1 pos))])
      (cond
        [(= status #xFF)
         (define meta-type (bytes-ref data pos))
         (set! pos (add1 pos))
         (define-values (mlen p2) (read-vlq data pos))
         (set! pos p2)
         (define mdata (subbytes data pos (+ pos mlen)))
         (set! pos (+ pos mlen))
         (cond
           [(and (= meta-type #x58) (>= (bytes-length mdata) 2))
            (define nn (bytes-ref mdata 0))
            (define dd (bytes-ref mdata 1))
            (define denom (expt 2 dd))
            (push! (evt abs-tick 'time-signature #f nn denom))]
           [(and (= meta-type #x59) (>= (bytes-length mdata) 2))
            (define sf (integer-bytes->integer (subbytes mdata 0 1) #t #t))
            (define mi (bytes-ref mdata 1))
            (push! (evt abs-tick 'key-signature #f sf mi))]
           [(= meta-type #x03)
            (define name (bytes->string/utf-8 mdata))
            (push! (evt abs-tick 'track-name #f name #f))])]
        [(or (= status #xF0) (= status #xF7))
         (define-values (slen p2) (read-vlq data pos))
         (set! pos (+ p2 slen))]
        [else
         (define kind (bitwise-and status #xF0))
         (define chan (bitwise-and status #x0F))
         (define (read-data1)
           (cond
             [data1 data1]
             [else (define v (bytes-ref data pos))
                   (set! pos (add1 pos))
                   v]))
         (define (read-data2)
           (define v (bytes-ref data pos))
           (set! pos (add1 pos))
           v)
         (define d1 (read-data1))
         (define d2 (if (or (= kind #xC0) (= kind #xD0)) #f (read-data2)))
         (define ev-kind
           (case kind
             [(#x80) 'note-off]
             [(#x90) (if (and d2 (= d2 0)) 'note-off 'note-on)]
             [else 'other]))
         (when (memq ev-kind '(note-on note-off))
           (push! (evt abs-tick ev-kind chan d1 d2)))])
      (loop)))
  (reverse events))

(define (parse-midi path)
  (define b (call-with-input-file path port->bytes))
  (define pos 0)
  (define (read-chunk-id)
    (define id (bytes->string/utf-8 (subbytes b pos (+ pos 4))))
    (set! pos (+ pos 4))
    id)
  (define (read-chunk-data)
    (define-values (len p1) (read-u32be b pos))
    (set! pos p1)
    (define data (subbytes b pos (+ pos len)))
    (set! pos (+ pos len))
    data)

  (define hdr (read-chunk-id))
  (unless (string=? hdr "MThd")
    (error 'parse-midi "missing MThd header"))
  (define hdata (read-chunk-data))
  (define-values (fmt p1) (read-u16be hdata 0))
  (define-values (ntrks p2) (read-u16be hdata p1))
  (define-values (division _) (read-u16be hdata p2))

  (define tracks '())
  (for ([i (in-range ntrks)])
    (define tid (read-chunk-id))
    (unless (string=? tid "MTrk")
      (error 'parse-midi "missing MTrk at track ~a" i))
    (define tdata (read-chunk-data))
    (set! tracks (cons (parse-track-data tdata) tracks)))
  (values fmt ntrks division (reverse tracks)))

(define (time-signatures-from-tracks tracks)
  (define sigs '())
  (for ([evts tracks])
    (for ([e evts])
      (when (eq? (evt-kind e) 'time-signature)
        (set! sigs (cons (list (evt-tick e) (evt-a e) (evt-b e)) sigs)))))
  (sort sigs < #:key first))

(define (track-names-from-tracks tracks)
  (define names (make-hash))
  (for ([evts tracks] [ti (in-naturals 0)])
    (for ([e evts])
      (when (eq? (evt-kind e) 'track-name)
        (hash-set! names ti (evt-a e)))))
  names)

(define (key-signatures-from-tracks tracks)
  (define sigs '())
  (for ([evts tracks])
    (for ([e evts])
      (when (eq? (evt-kind e) 'key-signature)
        (set! sigs (cons (list (evt-tick e) (evt-a e) (evt-b e)) sigs)))))
  (sort sigs < #:key first))

;; ---------- note extraction ----------
(define (notes-from-track evts track-index)
  (define open (make-hash))
  (define notes '())
  (for ([e evts])
    (when (memq (evt-kind e) '(note-on note-off))
      (define key (list (evt-chan e) (evt-a e)))
      (cond
        [(eq? (evt-kind e) 'note-on)
         (hash-set! open key (cons (evt-tick e) (hash-ref open key '())))]
        [else
         (define starts (hash-ref open key '()))
         (when (pair? starts)
           (define st (car starts))
           (hash-set! open key (cdr starts))
           (set! notes (cons (note track-index (evt-chan e) (evt-a e) st (evt-tick e)) notes)))])))
  (sort notes < #:key note-start))

;; ---------- duration mapping ----------
(define (duration-table ppq)
  (define q ppq)
  (define e (/ ppq 2))
  (define s (/ ppq 4))
  (define dq (+ q e))
  (define de (+ e s))
  (define ds (+ s (/ s 2)))
  (list (cons 'dq dq)
        (cons 'q q)
        (cons 'de de)
        (cons 'e e)
        (cons 'ds ds)
        (cons 's s)))

(define (quantize ticks s)
  (define q (inexact->exact (round (/ ticks s))))
  (* q s))

(define (split-duration ticks table)
  (define rem ticks)
  (define out '())
  (define min-ticks (cdr (last table)))
  (let loop ()
    (when (> rem 0)
      (define chosen
        (for/first ([d table] #:when (<= (cdr d) rem)) d))
      (define use (if chosen chosen (cons (caar (last table)) min-ticks)))
      (set! out (cons use out))
      (set! rem (- rem (cdr use)))
      (loop)))
  (reverse out))

(define (duration-symbol sym rest?)
  (define base (symbol->string sym))
  (string->symbol (if rest? (string-append base "r") base)))

(define (pitch->symbol pitch prefer-flats?)
  (define sharp '#("c" "cs" "d" "ds" "e" "f" "fs" "g" "gs" "a" "as" "b"))
  (define flat  '#("c" "df" "d" "ef" "e" "f" "gf" "g" "af" "a" "bf" "b"))
  (define names (if prefer-flats? flat sharp))
  (define pc (modulo pitch 12))
  (define octave (- (quotient pitch 12) 1))
  (string->symbol (format "~a~a" (vector-ref names pc) octave)))

;; ---------- bar formatting ----------
(define (bar-length ppq time-sigs)
  (define sig (if (null? time-sigs) (list 0 4 4) (first time-sigs)))
  (define num (second sig))
  (define denom (third sig))
  (inexact->exact (/ (* ppq num 4) denom)))

(define (sequence-from-notes notes ppq bar-ticks)
  (define s (/ ppq 4))
  (define seq '())
  (define cur 0)
  (for ([n notes])
    (define st (quantize (note-start n) s))
    (define en (quantize (note-end n) s))
    (when (< cur st)
      (set! seq (cons (cons (- st cur) 0) seq)))
    (when (> en st)
      (set! seq (cons (cons (- en st) (note-pitch n)) seq)))
    (set! cur en))
  (when (and (> cur 0) (not (= (modulo cur bar-ticks) 0)))
    (define pad (- bar-ticks (modulo cur bar-ticks)))
    (set! seq (cons (cons pad 0) seq)))
  (reverse seq))

(define (split-into-bars seq bar-ticks)
  (define bars '())
  (define cur '())
  (define rem bar-ticks)
  (for ([ev seq])
    (define ticks (car ev))
    (define pitch (cdr ev))
    (let loop ([t ticks])
      (cond
        [(<= t rem)
         (set! cur (cons (cons t pitch) cur))
         (set! rem (- rem t))]
        [else
         (set! cur (cons (cons rem pitch) cur))
         (set! bars (cons (reverse cur) bars))
         (set! cur '())
         (set! t (- t rem))
         (set! rem bar-ticks)
         (loop t)])))
  (when (pair? cur)
    (set! bars (cons (reverse cur) bars)))
  (reverse bars))

(define (render-track-bars notes ppq bar-ticks prefer-flats?)
  (define table (duration-table ppq))
  (define seq (sequence-from-notes notes ppq bar-ticks))
  (define bars (split-into-bars seq bar-ticks))
  (for/list ([bar bars])
    (define parts '())
    (for ([ev bar])
      (define ticks (car ev))
      (define pitch (cdr ev))
      (define chunks (split-duration ticks table))
      (for ([c chunks])
        (define sym (duration-symbol (car c) (= pitch 0)))
        (define pval (if (= pitch 0) "0" (symbol->string (pitch->symbol pitch prefer-flats?))))
        (set! parts (cons (format "(cons ~a ~a)" sym pval) parts))))
    (string-join (reverse parts) " ")))

(define (export-midi path)
  (define-values (_fmt _ntrks ppq tracks) (parse-midi path))
  (define time-sigs (time-signatures-from-tracks tracks))
  (define track-names (track-names-from-tracks tracks))
  (define key-sigs (key-signatures-from-tracks tracks))
  (define prefer-flats? (and (pair? key-sigs) (< (second (first key-sigs)) 0)))
  (define bar-ticks (bar-length ppq time-sigs))
  (for/list ([evts tracks] [ti (in-naturals 0)])
    (define notes (notes-from-track evts ti))
    (define bars (render-track-bars notes ppq bar-ticks prefer-flats?))
    (list ti (hash-ref track-names ti #f) bars)))

(define (safe-id s)
  (define lower (string-downcase s))
  (define cleaned (regexp-replace* #rx"[^a-z0-9]+" lower "-"))
  (define trimmed (regexp-replace* #rx"^-+|-+$" cleaned ""))
  (if (string=? trimmed "") "track" trimmed))

(define (emit-rackmuse path)
  (define tracks (export-midi path))
  (define used (make-hash))
  (for ([t tracks])
    (define ti (first t))
    (define tname (second t))
    (define bars (third t))
    (define base (if tname (safe-id tname) (format "track-~a" ti)))
    (define idx (hash-ref used base 0))
    (hash-set! used base (add1 idx))
    (define name (if (= idx 0) base (format "~a-~a" base idx)))
    (displayln (format "(define ~a" name))
    (displayln "  (list")
    (for ([line bars] [i (in-naturals 1)])
      (displayln (format "   ~a ; bar ~a" line i)))
    (displayln "  ))")
    (newline)))

(module+ main
  (define args (vector->list (current-command-line-arguments)))
  (define path (and (pair? args) (car args)))
  (unless path
    (displayln "Usage: racket rackmuse_export.rkt <file.mid>")
    (exit 1))
  (emit-rackmuse path))
